# Generated by VaultCraft MCP for containerized deployment
FROM python:3.12-slim

WORKDIR /app

# Install build dependencies
RUN pip install --no-cache-dir hatchling

# Copy project files
COPY pyproject.toml README.md ./
COPY src/ ./src/

# Install VaultCraft package
RUN pip install --no-cache-dir .

# Default vault directory inside container
ENV VAULTCRAFT_PATH=/data/vault
VOLUME ["/data/vault"]

ENTRYPOINT ["vaultcraft"]
